#pragma once

#include "../UniResolver.h"

// This is a small excerpt of an SDK generated by UniDumper. Metadata tokens and
// available methods depend on the target Unity version; regenerate the SDK for
// the game being inspected instead of copying these values into another project.

namespace System
{
	// Name: System::Object
	// ClassType: Normal
	class Object
	{
	public:
		CLASS("mscorlib", "System", Object);

		void* klass;   // 0x0000 (0x0008)
		void* monitor; // 0x0008 (0x0008)
	};
}

namespace UnityEngine
{
	// Name: UnityEngine::Object
	// ClassType: Normal
	// Inheritance: UnityEngine::Object -> System::Object
	class Object : public System::Object
	{
	public:
		CLASS("UnityEngine.CoreModule", "UnityEngine", Object);

		std::intptr_t m_CachedPtr; // 0x0010 (0x0008)
	};

	// Name: UnityEngine::Application
	// ClassType: Normal
	// Inheritance: UnityEngine::Application -> System::Object
	class Application : public System::Object
	{
	public:
		CLASS("UnityEngine.CoreModule", "UnityEngine", Application);

		class LogCallback
		{
		public:
			NESTED_CLASS(Application, LogCallback);
		};

		STATIC_FIELD(LogCallback*, s_LogCallbackHandler);

		// Token: 0x0600006D
		METHOD_INFO(0x0600006D);
		static std::string get_unityVersion()
		{
			return Template::MethodInvoker<std::string>(
				__0x0600006D_Method_Info__.GetMethod())();
		}

		// Token: 0x0600006E
		METHOD_INFO(0x0600006E);
		static std::string get_version()
		{
			return Template::MethodInvoker<std::string>(
				__0x0600006E_Method_Info__.GetMethod())();
		}
	};
}
